POST http://localhost:3333/animes
Content-Type: application/json

{
  "name": "Jujutsu Kaisen",
  "urlImg": "https://m.media-amazon.com/images/I/811NcGVbE+L._AC_UF1000,1000_QL80_.jpg",
  "likes": 0
}

###

GET  http://localhost:3333/animes

###

PUT  http://localhost:3333/animes/276abaa4-9e55-4476-801c-ab96a1b5b938
Content-Type: application/json

{
  "name": "Jujutsu",
  "urlImg": "https://m.media-amazon.com/images/I/811NcGVbE+L._AC_UF1000,1000_QL80_.jpg",
  "likes": 1
}

###

DELETE  http://localhost:3333/animes/276abaa4-9e55-4476-801c-ab96a1b5b938


###

PUT  http://localhost:3333/add-like/04cdfa17-39fe-4f32-9165-797ba2caa161

###

GET  http://localhost:3333/animes